"""
Bias Report Export (HTML/PDF).

Generates formatted bias reports with embedded charts for stakeholder review. HTML is always available; PDF requires weasyprint.

Usage:
    exporter = BiasReportExporter()

    # From a ModelBiasReport
    html_path = exporter.export_html(bias_report, output_path="reports/bias.html")

    # From a full pipeline run (all components)
    html_path = exporter.export_full_report(
        model_report=model_bias_report,
        scoring_report=scoring_report,
        explanation_report=explanation_report,
        slice_report=slice_report,
        output_path="reports/full_bias_report.html",
    )

    # PDF (requires weasyprint)
    pdf_path = exporter.export_pdf(bias_report, output_path="reports/bias.pdf")
"""

from __future__ import annotations

import base64
import io
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    MPL_AVAILABLE = True
except ImportError:
    plt = None  # type: ignore[assignment]
    MPL_AVAILABLE = False


def _fig_to_base64(fig: Any) -> str:
    """Convert a matplotlib figure to base64-encoded PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    buf.seek(0)
    encoded = base64.b64encode(buf.read()).decode("utf-8")
    plt.close(fig)
    return encoded


def _fig_to_img_tag(fig: Any, alt: str = "chart") -> str:
    """Convert a matplotlib figure to an HTML <img> tag."""
    b64 = _fig_to_base64(fig)
    return (
        f'<img src="data:image/png;base64,{b64}" alt="{alt}" style="max-width:100%;">'
    )


# =====================================================================
# HTML template
# =====================================================================

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RewardSense Bias Report — {title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
               color: #1a1a1a; background: #f8f9fa; padding: 2rem; line-height: 1.6; }}
        .container {{ max-width: 1000px; margin: 0 auto; background: white;
                     padding: 2.5rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        h1 {{ color: #0072B2; margin-bottom: 0.5rem; font-size: 1.8rem; }}
        h2 {{ color: #333; margin: 2rem 0 1rem; padding-bottom: 0.5rem;
              border-bottom: 2px solid #0072B2; font-size: 1.3rem; }}
        h3 {{ color: #555; margin: 1.5rem 0 0.5rem; font-size: 1.1rem; }}
        .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
        .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                        gap: 1rem; margin: 1.5rem 0; }}
        .summary-card {{ background: #f0f7ff; border-radius: 6px; padding: 1rem;
                        text-align: center; border: 1px solid #d0e3f7; }}
        .summary-card .number {{ font-size: 2rem; font-weight: bold; color: #0072B2; }}
        .summary-card .label {{ font-size: 0.85rem; color: #555; }}
        .alert {{ background: #fff3e0; border-left: 4px solid #D55E00;
                 padding: 1rem; margin: 1rem 0; border-radius: 0 4px 4px 0; }}
        .pass {{ background: #e8f5e9; border-left: 4px solid #0072B2;
                padding: 1rem; margin: 1rem 0; border-radius: 0 4px 4px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }}
        th {{ background: #0072B2; color: white; padding: 0.6rem 0.8rem; text-align: left; }}
        td {{ padding: 0.5rem 0.8rem; border-bottom: 1px solid #e0e0e0; }}
        tr:nth-child(even) {{ background: #f8f9fa; }}
        .biased {{ color: #D55E00; font-weight: bold; }}
        .clean {{ color: #0072B2; }}
        .chart {{ margin: 1.5rem 0; text-align: center; }}
        .chart img {{ border-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
        .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0;
                  color: #999; font-size: 0.8rem; text-align: center; }}
    </style>
</head>
<body>
<div class="container">
    {content}
    <div class="footer">
        Generated by RewardSense Bias Detection Pipeline — {timestamp}
    </div>
</div>
</body>
</html>"""


# =====================================================================
# BiasReportExporter
# =====================================================================


class BiasReportExporter:
    """Export bias reports to HTML and PDF with embedded visualizations."""

    def __init__(self) -> None:
        if not MPL_AVAILABLE:
            logger.warning("matplotlib not installed — reports will have no charts")

    # ------------------------------------------------------------------
    # HTML generation helpers
    # ------------------------------------------------------------------

    def _render_summary_cards(self, cards: Dict[str, Any]) -> str:
        html = '<div class="summary-grid">'
        for label, value in cards.items():
            html += (
                f'<div class="summary-card">'
                f'<div class="number">{value}</div>'
                f'<div class="label">{label}</div></div>'
            )
        html += "</div>"
        return html

    def _render_metrics_table(self, metrics: List[Dict[str, Any]]) -> str:
        if not metrics:
            return '<p class="pass">No metrics to display.</p>'

        html = "<table><tr><th>Metric</th><th>Feature</th><th>Value</th><th>Threshold</th><th>Status</th></tr>"
        for m in metrics:
            name = m.get("name", m.get("check", ""))
            feat = m.get("sensitive_feature", m.get("feature", ""))
            val = m.get("value", 0)
            thresh = m.get("threshold", "—")
            biased = m.get("is_biased", False)
            status_cls = "biased" if biased else "clean"
            status_txt = "FLAGGED" if biased else "PASS"
            html += (
                f"<tr><td>{name}</td><td>{feat}</td>"
                f"<td>{val:.4f}</td><td>{thresh}</td>"
                f'<td class="{status_cls}">{status_txt}</td></tr>'
            )
        html += "</table>"
        return html

    # ------------------------------------------------------------------
    # Model Bias Report
    # ------------------------------------------------------------------

    def _render_model_bias(self, report: Any) -> str:
        """Render ModelBiasReport section."""
        d = report.to_dict()
        summary = d.get("summary", {})

        html = "<h2>Model Bias Detection</h2>"
        html += self._render_summary_cards(
            {
                "Total Checks": summary.get("total_metrics", 0),
                "Flagged": summary.get("biased", 0),
                "Clean": summary.get("unbiased", 0),
            }
        )

        if summary.get("biased", 0) > 0:
            html += '<div class="alert">Bias detected in model predictions. Review flagged metrics below.</div>'
        else:
            html += '<div class="pass">All bias checks passed.</div>'

        html += "<h3>All Metrics</h3>"
        table_metrics = [
            {
                "name": m.name,
                "sensitive_feature": m.sensitive_feature,
                "value": m.value,
                "threshold": m.threshold,
                "is_biased": m.is_biased,
            }
            for m in report.metrics
        ]
        html += self._render_metrics_table(table_metrics)

        # Charts
        if MPL_AVAILABLE:
            try:
                from src.model_pipeline.bias.visualizations import (
                    plot_bias_summary,
                    plot_fairness_metrics,
                )

                # Build chart data directly from report object
                chart_metrics = [
                    {
                        "name": m.name,
                        "sensitive_feature": m.sensitive_feature,
                        "value": m.value,
                        "threshold": m.threshold,
                        "is_biased": m.is_biased,
                    }
                    for m in report.metrics
                ]

                if chart_metrics:
                    fig = plot_bias_summary(chart_metrics)
                    html += f'<div class="chart">{_fig_to_img_tag(fig, "Bias Summary")}</div>'

                if report.per_group_metrics:
                    fig = plot_fairness_metrics(report.per_group_metrics)
                    html += f'<div class="chart">{_fig_to_img_tag(fig, "Fairness Breakdown")}</div>'
            except Exception as e:
                logger.warning("Chart generation failed: %s", e)

        return html

    # ------------------------------------------------------------------
    # Scoring Bias Report
    # ------------------------------------------------------------------

    def _render_scoring_bias(self, report: Any) -> str:
        d = report.to_dict()
        summary = d.get("summary", {})

        html = "<h2>Scoring Engine Bias</h2>"
        html += self._render_summary_cards(
            {
                "Checks": summary.get("total_checks", 0),
                "Flagged": summary.get("biased", 0),
                "Clean": summary.get("clean", 0),
            }
        )

        metrics = d.get("metrics", [])
        html += self._render_metrics_table(metrics)

        if MPL_AVAILABLE:
            try:
                from src.model_pipeline.bias.visualizations import (
                    plot_issuer_distribution,
                )

                fig = plot_issuer_distribution(metrics)
                html += f'<div class="chart">{_fig_to_img_tag(fig, "Issuer Distribution")}</div>'
            except Exception as e:
                logger.warning("Scoring chart failed: %s", e)

        return html

    # ------------------------------------------------------------------
    # Explanation Bias Report
    # ------------------------------------------------------------------

    def _render_explanation_bias(self, report: Any) -> str:
        d = report.to_dict()
        summary = d.get("summary", {})

        html = "<h2>LLM Explanation Bias</h2>"
        html += self._render_summary_cards(
            {
                "Checks": summary.get("total_checks", 0),
                "Flagged": summary.get("biased", 0),
                "Clean": summary.get("clean", 0),
            }
        )

        metrics = d.get("metrics", [])
        html += self._render_metrics_table(metrics)

        if MPL_AVAILABLE:
            try:
                from src.model_pipeline.bias.visualizations import (
                    plot_explanation_quality,
                )

                fig = plot_explanation_quality(metrics)
                html += f'<div class="chart">{_fig_to_img_tag(fig, "Explanation Quality")}</div>'
            except Exception as e:
                logger.warning("Explanation chart failed: %s", e)

        return html

    # ------------------------------------------------------------------
    # Slice Evaluation Report
    # ------------------------------------------------------------------

    def _render_slice_report(self, report: Any) -> str:
        d = report.to_dict()

        html = "<h2>Per-Slice Evaluation</h2>"
        html += self._render_summary_cards(
            {
                "Slices": d.get("summary", {}).get("total_slices", 0),
                "Disparities": d.get("summary", {}).get("disparities_found", 0),
            }
        )

        # Slice table
        slices = d.get("slices", [])
        if slices:
            metrics_keys = list(slices[0].get("metrics", {}).keys())
            html += "<table><tr><th>Slice</th><th>Count</th><th>Fraction</th>"
            for k in metrics_keys:
                html += f"<th>{k}</th>"
            html += "</tr>"
            for s in slices:
                html += f"<tr><td>{s['name']}</td><td>{s['count']}</td><td>{s['fraction']:.2%}</td>"
                for k in metrics_keys:
                    html += f"<td>{s['metrics'].get(k, 0):.4f}</td>"
                html += "</tr>"
            html += "</table>"

        if MPL_AVAILABLE:
            try:
                from src.model_pipeline.bias.visualizations import (
                    plot_slice_metrics,
                    plot_disparity_heatmap,
                )

                overall = d.get("overall_metrics", {})
                fig = plot_slice_metrics(slices, overall=overall)
                html += (
                    f'<div class="chart">{_fig_to_img_tag(fig, "Slice Metrics")}</div>'
                )

                if overall:
                    fig = plot_disparity_heatmap(slices, overall)
                    html += f'<div class="chart">{_fig_to_img_tag(fig, "Disparity Heatmap")}</div>'
            except Exception as e:
                logger.warning("Slice chart failed: %s", e)

        return html

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def export_html(
        self,
        report: Any,
        output_path: str | Path = "reports/bias_report.html",
        title: str = "Model Bias Report",
    ) -> Path:
        """
        Export a single bias report to HTML.

        Parameters
        ----------
        report : ModelBiasReport, ComponentBiasReport, or SliceEvaluationReport
        output_path : str or Path
        title : str

        Returns
        -------
        Path to the generated HTML file.
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        content = f"<h1>{title}</h1>"
        content += f'<div class="meta">Generated: {ts}</div>'

        report_type = type(report).__name__
        if "ModelBiasReport" in report_type:
            content += self._render_model_bias(report)
        elif "ComponentBiasReport" in report_type:
            if report.component == "scoring_engine":
                content += self._render_scoring_bias(report)
            else:
                content += self._render_explanation_bias(report)
        elif "SliceEvaluation" in report_type:
            content += self._render_slice_report(report)
        else:
            content += f"<pre>{report.to_dict()}</pre>"

        html = HTML_TEMPLATE.format(
            title=title,
            content=content,
            timestamp=ts,
        )
        output_path.write_text(html, encoding="utf-8")
        logger.info("HTML report exported: %s", output_path)
        return output_path

    def export_full_report(
        self,
        model_report: Optional[Any] = None,
        scoring_report: Optional[Any] = None,
        explanation_report: Optional[Any] = None,
        slice_report: Optional[Any] = None,
        output_path: str | Path = "reports/full_bias_report.html",
        title: str = "RewardSense — Full Bias Analysis",
    ) -> Path:
        """
        Export a comprehensive report covering all components.

        Returns
        -------
        Path to the generated HTML file.
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        content = f"<h1>{title}</h1>"
        content += f'<div class="meta">Generated: {ts}</div>'

        # Executive summary
        total_checks = 0
        total_flagged = 0
        for r in [model_report, scoring_report, explanation_report]:
            if r is not None and hasattr(r, "metrics"):
                total_checks += len(r.metrics)
                total_flagged += len(r.biased_metrics)

        content += self._render_summary_cards(
            {
                "Total Checks": total_checks,
                "Flagged": total_flagged,
                "Pass Rate": (
                    f"{(total_checks - total_flagged) / total_checks:.0%}"
                    if total_checks > 0
                    else "N/A"
                ),
            }
        )

        if total_flagged > 0:
            content += '<div class="alert">Bias detected. Review individual component reports below.</div>'
        else:
            content += (
                '<div class="pass">All bias checks passed across all components.</div>'
            )

        if slice_report is not None:
            content += self._render_slice_report(slice_report)
        if model_report is not None:
            content += self._render_model_bias(model_report)
        if scoring_report is not None:
            content += self._render_scoring_bias(scoring_report)
        if explanation_report is not None:
            content += self._render_explanation_bias(explanation_report)

        html = HTML_TEMPLATE.format(
            title=title,
            content=content,
            timestamp=ts,
        )
        output_path.write_text(html, encoding="utf-8")
        logger.info("Full bias report exported: %s", output_path)
        return output_path

    def export_pdf(
        self,
        report: Any,
        output_path: str | Path = "reports/bias_report.pdf",
        title: str = "Model Bias Report",
    ) -> Path:
        """
        Export a bias report to PDF via weasyprint.

        Requires: pip install weasyprint

        Returns
        -------
        Path to the generated PDF file.
        """
        try:
            from weasyprint import HTML as WeasyprintHTML
        except ImportError:
            raise ImportError(
                "weasyprint required for PDF export: pip install weasyprint"
            )

        # Generate HTML first, then convert
        html_path = Path(str(output_path).replace(".pdf", ".html"))
        self.export_html(report, html_path, title)

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        WeasyprintHTML(filename=str(html_path)).write_pdf(str(output_path))
        logger.info("PDF report exported: %s", output_path)
        return output_path
